### ISSUE TITLE
Fluxctl 1.3.0 crash on OSX

### ISSUE THREAD

**Issue by marcuslindfeldt** [weaveworks/flux#1087]
fluxctl_darwin_amd64 v1.3.0 fatal crash

```
panic: runtime error: index out of range

goroutine 1 [running]:
main.userGitconfigMap(0xc4200b8580, 0xc57, 0xc57)
	/go/src/github.com/weaveworks/flux/cmd/fluxctl/args.go:60 +0x232
main.getUserGitconfig(0x3d)
	/go/src/github.com/weaveworks/flux/cmd/fluxctl/args.go:48 +0x175
main.AddCauseFlags(0xc42032a480, 0xc4200ea758)
	/go/src/github.com/weaveworks/flux/cmd/fluxctl/args.go:15 +0x26
main.(*controllerReleaseOpts).Command(0xc4200ea6e0, 0xc4200ea6e0)
	/go/src/github.com/weaveworks/flux/cmd/fluxctl/release_cmd.go:46 +0x1a5
main.(*rootOpts).Command(0xc4203193e0, 0xc4203193e0)
	/go/src/github.com/weaveworks/flux/cmd/fluxctl/root_cmd.go:62 +0x53b
main.run(0xc420094090, 0x1, 0x1, 0xc4200001a0)
	/go/src/github.com/weaveworks/flux/cmd/fluxctl/main.go:12 +0x4d
main.main()
	/go/src/github.com/weaveworks/flux/cmd/fluxctl/main.go:29 +0x64
```

**Comment by marcuslindfeldt** [comment]
Fixed it by removing a multiline alias in my git config.

**Comment by squaremo** [comment]
Likely the same problem that prompted https://github.com/weaveworks/flux/pull/1073 -- I should do another release, to get that and other fixes into GA.

**Comment by squaremo** [comment]
(1.3.1 included this fix -- closing)
