### ISSUE TITLE
Not a ReplicationController or Deployment causing exit status 1?

### ISSUE THREAD

**Issue by BenHall** [weaveworks/flux#228]
When performing a Git commit, it's failing with an exit status 1. This looks to be as a result of having service and deployment yaml in the same Github repo directory.

Here is my flux release output:

```
Here's as far as we got:                                                                             
 1) Submitted job.                                                                                   
 2) Calculating release actions.                                                                     
 3) Release latest images to sock-shop/front-end                                                     
 4) Clone the config repo.                                                                           
 5) Clone OK.                                                                                        
 6) Update 1 images(s) in the resource definition file for sock-shop/front-end: front-end (registry.t
est.training.katacoda.com:4567/root/front-end:latest -> registry.test.training.katacoda.com:4567/root
/front-end:49ba055e74fadff960e40484fba3d52704f613c9).                                                
 7) Update pod controller OK.                                                                        
 8) Commit and push the config repo.                                                                 
 9) git commit: exit status 1                                                                        
 10) Failed: git commit: exit status 1
```

This is from the fluxsvc logs it looks to be related to this:

```
kubeservice FAILED: exit status 1
Args: [/usr/local/bin/kubeservice ./cart-svc.yaml]                                                   
Dir: /tmp/flux-gitclone576714826/repo/deploy/kubernetes/manifests                                    
ts=2016-11-09T13:01:31Z caller=transport.go:717 method=GetRelease url="/v3/release?id=f45b1753-b27a-a8c6-0704-1bdde6a9de47" took=391.785µs status_code=200                                                
                                                                                                     
Traceback (most recent call last):                                                                   
  File "/usr/local/bin/kubeservice", line 93, in <module>                                            
    for service in service_for_file(args[0]):                                                        
  File "/usr/local/bin/kubeservice", line 63, in service_for_file                                    
    raise Kubeimage("Not a ReplicationController or Deployment")                                     
__main__.Kubeimage: Not a ReplicationController or Deployment   
```

The repo is a local clone of https://github.com/microservices-demo/microservices-demo/tree/master/deploy/kubernetes/manifests

**Comment by squaremo** [comment]
The `exit(1)` occurs in a later part of the process, when it tries to commit the changes -- that's probably further down in the logs (which are long gone by now I expect!).

With respect to `kubeservice`, though:

Part of the problem is that we're abusing `kubeservice` -- it does things the wrong way around, by looking for the service that corresponds to a deployment, rather than the deployment that corresponds to a service, so it gets run repeatedly on every file to see if it comes up with the right answer (with exit 1 indicating a wrong answer). See #139.

Another part of the problem is that we log its output, which is frequently harmlessly a stack trace as above. If we continue to use kubeservice we should at least log only meaningful output.

**Comment by BenHall** [comment]
Ah, ok. I just noticed exit 1. Next time I'll dump the entire log.

**Comment by philwinder** [comment]
This is probably due to invalid git credentials/keys. Closing due to inactivity.
