### ISSUE TITLE
Putting quotes in repo argument crashes fluxy

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#93]
e.g., if you have `--repo-path="testdata"` it crashes with something like

```
2016-08-19 12:51:28.064642 I | http: panic serving 172.20.0.9:52008: runtime error: invalid memory address or nil pointer dereference
goroutine 60 [running]:
net/http.(*conn).serve.func1(0xc820064600)
           /usr/lib/go-1.6/src/net/http/server.go:1389 +0xc1
panic(0x1a59a20, 0xc820018060)
           /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/weaveworks/fluxy/git.findFileFor.func1(0xc822640320, 0x41, 0x0, 0x0, 0x7f4b25679180, 0xc82057cea0, 0x0, 0x0)
           /home/mikeb/space/fluxy-gopath/src/github.com/weaveworks/fluxy/git/releasing.go:127 +0x5b
path/filepath.Walk(0xc822640320, 0x41, 0xc823120d00, 0x0, 0x0)
           /usr/lib/go-1.6/src/path/filepath/path.go:394 +0xa5
github.com/weaveworks/fluxy/git.findFileFor(0xc82057cd20, 0x21, 0x7ffda6ffb1fa, 0x1f, 0xc8226400a0, 0x18, 0x0, 0x0, 0x0, 0x0)
           /home/mikeb/space/fluxy-gopath/src/github.com/weaveworks/fluxy/git/releasing.go:139 +0x1b6
github.com/weaveworks/fluxy/git.Repo.Release(0x7ffda6ffb194, 0x2c, 0x7ffda6ffb1cc, 0x21, 0x7ffda6ffb1fa, 0x1f, 0xc82057c1e0, 0xc82042f140, 0xc8217ba337, 0x7, ...)
           /home/mikeb/space/fluxy-gopath/src/github.com/weaveworks/fluxy/git/releasing.go:50 +0x463
github.com/weaveworks/fluxy.(*service).Release.func2(0x0, 0x0)
           /home/mikeb/space/fluxy-gopath/src/github.com/weaveworks/fluxy/service.go:166 +0x146
...
```

when you try to release something.

**Comment by paulbellamy** [comment]
This might be fixed. See if it still affects config stuff

**Comment by paulbellamy** [comment]
This is fixed by virtue of using yaml.
