### ISSUE TITLE
Weave-flux pod crashing looping with panic:

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#958]
```
ts=2018-02-22T11:58:38.568263415Z caller=release.go:100 component=platform method=Sync cmd="kubectl apply -f -" took=3.656547872s err=null output="deployment \"dashboard\" configured\nrole \"fluentd\" configured\ningress \"event-api\" configured\nservice \"default-http-backend\" configured\ndeployment \"goto-nrw\" configured\nservice \"goto-nrw\" configured\nserviceaccount \"nginx-ingress-serviceaccount\" configured\ningress \"klima-api\" configured\nservice \"klima-api\" configured\nrolebinding \"nginx-ingress-role-nisa-binding\" configured\ndeployment \"klima-api\" configured\nconfigmap \"nginx-configuration\" configured\nserviceaccount \"helm\" configured\ndaemonset \"nginx-ingress-controller\" configured\ningress \"dashboard\" configured\ningress \"traffics\" configured\ncronjob \"unims-scraper\" configured\ningress \"goto-nrw\" configured\nconfigmap \"udp-services\" configured\nrole \"nginx-ingress-role\" configured\nservice \"event-api\" configured\ndeployment \"default-http-backend\" configured\nservice \"traffics\" configured\nrolebinding \"fluentd\" configured\ndaemonset \"weave-net\" configured\njob \"unims-scraper\" configured\nservice \"dashboard\" configured\nconfigmap \"tcp-services\" configured\ndeployment \"event-api\" configured\ndeployment \"traffics\" configured"
ts=2018-02-22T11:58:38.568485016Z caller=loop.go:164 component=sync-loop err="default:list/: running kubectl: error: the namespace from the provided object \"kube-system\" does not match the namespace \"default\". You must pass '--namespace=kube-system' to perform this operation."
ts=2018-02-22T11:58:38.598793855Z caller=daemon.go:461 component=daemon event="Sync: 502b797..7892738, default:clusterissuer/letsencrypt, default:clusterrole/r2-cert-manager, default:clusterrolebinding/r2-cert-manager, default:customresourcedefinition/certificates.certmanager.k8s.io, default:customresourcedefinition/clusterissuers.certmanager.k8s.io, default:customresourcedefinition/issuers.certmanager.k8s.io, default:deployment/r2-cert-manager, default:ingress/kibana, default:ingress/kibana-auth, default:serviceaccount/r2-cert-manager" logupstream=true
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf03876]

goroutine 77 [running]:
github.com/weaveworks/flux/vendor/github.com/go-logfmt/logfmt.safeError.func1(0x1a41700, 0xc4203bea80, 0xc422421070, 0xc422421080)
    /go/src/github.com/weaveworks/flux/vendor/github.com/go-logfmt/logfmt/encode.go:281 +0x107
panic(0x1168440, 0x1a9d8f0)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
[...]
```

From user report in Slack:

> [...] `weave-flux` worked fine for maybe two weeks. I think this error showed up after I deployed new stuff on the server.

**Comment by stefanprodan** [comment]
Could be related to #949

**Comment by rade** [comment]
Neither this not #949 actually have the part of the stack trace that is interesting :(

I think it's a fair bet that the CRD is triggering this, which would make it a dup of #949.
